{% set name = "portalocker" %}
{% set version = "1.3.0" %}
{% set sha256 = "b5ba72ace4f50093e3841c65a24f65d4f1bddd8d47cf439e56ab30b1aebd62a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - portalocker

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF
  license_family: PSF
  license_file: LICENSE
  summary: 'Portalocker is a library to provide an easy API to file locking.'
  doc_url: http://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - sodre
