{% set name = "portalocker" %}
{% set version = "4.1.0" %}
{% set deselect_tests = " --deselect=portalocker_tests/test_combined.py::test_combined" %}

# Won`t copy README.rst to the sp_dir:
# E       FileNotFoundError: [Errno 2] No such file or directory: '$PREFIX/lib/python3.10/site-packages/README.rst'
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91d0ff02d6f5f9a2dbf1ef1367ddb05b83136b2676707a1b2c8746f1f0dcd992

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - uv_build >=0.11,<0.13
  run:
    - python
    - pywin32 >=226  # [win]
  run_constrained:
    - redis-py >=5.0

test:
  source_files:
    - portalocker_tests
  imports:
    - portalocker
  commands:
    - pip check
    - pytest -v portalocker_tests {{ deselect_tests }}
  requires:
    - pip
    - pytest >=5.4.1
    - redis-py

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Portalocker is a library to provide an easy API to file locking.
  description: |
    An easy library for Python file locking. It works on Windows, Linux, BSD and Unix systems and can even perform distributed locking. Naturally it also supports the with statement.
  doc_url: https://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - sodre
