{% set name = "portalocker" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f3002956a54a8c3730586c5c77bf18fae4149e07eaf1c29fc3faf4d5a3f89ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools-scm
  run:
    - python
    - pywin32 >=226  # [win]
    - pywin32-on-windows >=226  # [win]

test:
  source_files:
    - portalocker_tests
  imports:
    - portalocker
  requires:
    - pip
    - pytest
    - redis-py
  commands:
    - pip check
    - pytest -v portalocker_tests --ignore=portalocker_tests/test_combined.py

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Portalocker is a library to provide an easy API to file locking.
  description: |
    An easy library for Python file locking. It works on Windows, Linux, BSD and Unix systems and can even perform distributed locking. Naturally it also supports the with statement.
  doc_url: https://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - sodre
