{% set name = "portalocker" %}
{% set version = "1.4.0" %}
{% set sha256 = "3fb35648a9e03f267e54c6186513abbd1cdd321c305502545a3550eea8b2923f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pywin32 #[win]

test:
  imports:
    - portalocker

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF
  license_family: PSF
  license_file: LICENSE
  summary: 'Portalocker is a library to provide an easy API to file locking.'
  doc_url: http://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - sodre
