{% set name = "portalocker" %}
{% set version = "1.2.0" %}
{% set sha256 = "37c7d2b8eaf73a779089d8455ad90b0a38afd33e4fb8dedabe49e49550846173" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  imports:
    - portalocker

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF
  license_family: PSF
  license_file: LICENSE
  summary: 'Portalocker is a library to provide an easy API to file locking.'
  doc_url: http://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - sodre
