travis:
  secure:
    BINSTAR_TOKEN: omTssn3Rg6LmFGK96dgneiupB6HYfPgQ17s2Y4keckEzxZ65CcOjb/8dfW9aR2XMCFQy6w+QjwFylABG0gSEp8qr2ilAWmxYhCDmcb6ZspCnAk1G92hBfjBn74004NmR99q+xx44GRGFfUa7p2fcXWN3gFg3HpUz40JnTuO9qYJ96nBFsHEPIM7D9YvnQ0sJ1Tp9jPNlKlDWc0yZcE8PUVIUZdaWI/dV+WqCAZ6HiaMHAIBkqXaBorI6nA2bjaHaJUp5ApyE1+I6KiB4P/GHINdC3C55WYEuDvRp+6m4m5YWJ8N4TUPds+HVe82O8Wgg1qaeboXcT78hwnRoA8HPfIcgUxVESTAGiubM5NI3MOVevzwSRkQlRddgNpXcxNBCdfKKhXPmaWLgQCXFOSWaFvHKzyIk0ctNJkqWpr4T/GR1j/A/oOB2AjK13U6LNjU0pXUyWxs9N9XzsJqILXOXaM9laggW23rWAKYfqx/O7q0+DM4u5ZJpB4A2x2CUvI+KVg5Md8easQwkgJHiES+95PEwYXtlXI4Le4rMToLnA0HzqrvXYzSDyg0qdiZEMrn9KHgB9y26PCN9OPah5ukvdfy3/mthhh8yEf7wL4CQJf+SZIn2U2vOKSP1Tpjcl2/0SaY30Kv+cwHUDF1X/gf27wlZPn2azsvtKNitrIqcWqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
