travis:
  secure:
    BINSTAR_TOKEN: OHfjE835BN0aqDwiVvyyEw4+bJNk5zR6lgoQ0EppdK80ksyWyymPmuFI+KOW9ReQYo1hbBqmJqFaQbxr8w29qTjmv/xfSMXUuRBLbAwJYIy+q+P9eMm2HIwDqa35uPjhjyQwAYjUL6uW1AJTqP3v95Vshd/XMgmvMeDzvCOijbJZWPh09xKd2vCX+qf7ximla9HKpDtxv9IYMuruzr7pGkUiqACKUV9tmEW3r1inpv8vBG/unMUQk8fekzSg+rSF1Ru0nJaOl/DQyEahgWib3+DsSpHKwvS7RlHncT6jOOI26l1l6halBL7ANteXv7ssq/YiRAoG4ei8PK+3TPnw6NgV+gLBeD9TMNrVMkk5bhgBJCqq5fri5yOUH7Jn1HO1L3Mt4GTfFdtzaMjLzoLsYShai743SA3dPiC8kvV/Q9H22SMLCWK6mI0KArAja1NyuokxzOSTBoNYl4O6aNxEB336BQmIscobsUltV/yaJv/l0ts5ZqE88JhZK3vq4cNjVoJJZY+2qBNy0Q5OasfswG6mwrCboUzqSonjzyDQfubVIZ+oNUOxG0unPHyqHn9M+m/t+/GX64NVnAaNqa1ApqQLzrcJLHs9vyqrqc3Tq6gu5/X6grNYKQoRmdzoWSHTWZKXYokA/mtt52OIwLuWL2fduSbJdAPtHI/lNdsjV10=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
